# /worldcleaner reload - перезагрузить конфиг, право worldcleaner.command

# порог времени, до которого чанки будут удаляться
# что это за время? это количество тиков, которые чанк был в зоне видимости игрока
# по умолчанию 60 секунд - 1200 тиков. если игрок чанк видел менее 60 секунд, то чанк удаляется
inhabited-time-threshold-ticks: 1200